services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kostya2506/k-task:v1.0
    container_name: k-task-app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - 6969:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17-alpine
    container_name: postgres-db
    ports:image: kostya2506/k-task:v1.0
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  pg_data: